### ISSUE TITLE
Getting a 404 from https://www.reddit.com/prefs/feeds

### ISSUE THREAD

**Issue by garrrettt** [Friiiis/saved-posts-organizer#1]
`fetch('https://www.reddit.com/prefs/feeds')` on line 40 of popup.js returns a 404 for me

**Comment by Friiiis** [comment]
Have you tried visiting the link (https://www.reddit.com/prefs/feeds) in your browser? 

I would expect the fetch to return a 404 if your are not logged into reddit. If this is the case, the extension should show an error message at the bottom.

**Comment by garrrettt** [comment]
Yeah I visited the link in my browser, and it's still a 404 even when I'm logged in

**Comment by Friiiis** [comment]
How about this link:
https://old.reddit.com/prefs/feeds/

**Comment by garrrettt** [comment]
Still doesn't work (404). What does that page look like for you? 

Fortunately, that link isn't too important as far as the overall functionality of the extension

**Comment by Friiiis** [comment]
![image](https://user-images.githubusercontent.com/20768890/60448718-778e1000-9c26-11e9-9a62-f121c92d39c7.png)

It's a page that contains links to your personal RSS/JSON feeds. The extension actually uses this link to get the user's username and api key, which will be used in the url of the feed: "https://www.reddit.com/user/<username>/saved.json?feed=<api key>"

It's a bit of a hacky way to get the details, but it works for now. Hopefully reddit won't change this page too much :-)
